# Importing the Relevant Libraries

In [1]:
#Import the relevant libraries
import pandas as pd
import numpy as np
import pandas_profiling as pp
from IPython.display import IFrame

# Importing the Dataset

This dataset consists of survey results of grocery items conducted periodically islandwide by the Consumer Affairs Commission survey officers in Jamaica.

More specifically, this dataset consists of grocery prices observed in Q2 2018

In [2]:
#Our dataset is located here. Visit this link and download the dataset by clicking the 'Download' button
IFrame('https://data.gov.jm/dataset/consumer-grocery-prices/resource/9ffaa855-8d2b-485f-ade9-3d338fe4218a#{}', width=800, height=450)

In [3]:
#Load the dataset and view it
raw_data = pd.read_csv('Grocery_Prices_Survey_2018_Q2.csv')
raw_data

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
0,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] GRACE 340 g",4447347,326.62
1,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] NUPAK 340 g",4449647,284.87
2,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] EVE 340 g",4446447,294.62
3,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] LASCO 340 g",4448147,310.04
4,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] MIRACLE 340 g",4449247,266.19
5,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] CARIBBEAN ...",4482547,0.00
6,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] OTHER 340 g",4449747,308.70
7,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] GRACE...,6947334,79.41
8,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] BRUNS...,6944434,73.71
9,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] KENDE...,6982734,71.72
10,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] LASCO...,6948134,67.68
11,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] OTHER...,6949734,69.51
12,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (CANNED, In Soya Oil) [NT] BRUNSWICK ...",8744427,117.88
13,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (Canned, In Vegetable Oil) [NT] GRACE...",19147327,112.36
14,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (CANNED, In Soya Oil) [NT] OTHER 106 g",8749727,0.00
15,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,DRIED SALTED FISH [TX] BULK 1 kg,5344721,960.19
16,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHICKEN BACK [NT] LOCAL 1 kg,3948621,308.00
17,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHICKEN BACK [NT] IMPORTED 1 kg,3947521,187.00
18,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"WHOLE CHICKEN (Grade A, Frozen) [NT] BEST DRES...",10243821,477.20
19,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"WHOLE CHICKEN (Grade A, Frozen) [NT] CB 1 kg",10245121,456.30
20,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SKIMMED MILK POWDER [TX] LASCO - READIMILK 80 g,9050065,109.58
21,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,POWDERED WHOLE MILK [NT] LASCO 80 g,8048165,118.95
22,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,POWDERED WHOLE MILK [NT] ANCHOR 80 g,8043565,119.05
23,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SWEETENED CONDENSED MILK [TX] SERGE 392 g,91868123,272.84
24,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SWEETENED CONDENSED MILK [TX] BETTY 395 g,9144052,231.73
25,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] SERGE ISLAND 1 L,5750722,291.18
26,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] NESTLE 1 L,5749422,0.00
27,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] MIRACLE 1 L,5749222,245.45
28,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHEESE (Processed) [TX] TASTEE 1 kg,3851221,1735.12
29,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,INFANT FORMULA [NT] LASCO STEP 1 400 g,6348253,567.46
...,...,...,...,...,...,...,...,...
970,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,BLEACH [TX] CHLORITE 475 mL,3445557,0.00
971,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,BATH SOAP [TX] PALMOLIVE (Asssorted) 110 g,3149828,107.13
972,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.00
973,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SHAMPOO [TX] ALBERTO V05 370 g,89434442,0.00
974,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,LOTION [TX] JERGENS (Original Scent) 295 mL,6847744,413.53
975,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,LOTION [TX] VASELINE INTENSIVE CARE 295 mL,6851444,432.17
976,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,POWDER [TX] LANDER 113 g,7748029,202.66
977,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,POWDER [TX] JOHNSON'S BABY POWDER 113 g,7747929,313.34
978,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOILET TISSUE [TX] ANY 400 sheets,9581854,69.85
979,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHPASTE (Regular) [TX] COLGATE (Cavity Prot...,99458280,129.27
980,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHPASTE (Regular) [TX] LASCO (Advanced Cavi...,9969166,119.95
981,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHBRUSH [TX] COLGATE CLASSIC Each,9883069,0.00
982,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SANITARY NAPKINS [NT] STAYFREE MAXI (Regular w...,8650924,229.96
983,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SANITARY NAPKINS [NT] LIBRESSE MAXI (Regular W...,8648324,158.96
984,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] GRACE 340 g",4447347,377.00
985,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] NUPAK 340 g",4449647,311.00
986,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] EVE 340 g",4446447,306.00
987,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] LASCO 340 g",4448147,313.00
988,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] MIRACLE 340 g",4449247,273.00
989,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] CARIBBEAN ...",4482547,325.00
990,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] OTHER 340 g",4449747,320.00
991,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] GRACE...,6947334,76.00
992,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] BRUNS...,6944434,76.00
993,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] KENDE...,6982734,72.00
994,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] LASCO...,6948134,69.00
995,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] OTHER...,6949734,65.00
996,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (CANNED, In Soya Oil) [NT] BRUNSWICK ...",8744427,118.00
997,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (Canned, In Vegetable Oil) [NT] GRACE...",19147327,124.00
998,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (CANNED, In Soya Oil) [NT] OTHER 106 g",8749727,92.00
999,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,DRIED SALTED FISH [TX] BULK 1 kg,5344721,897.60

In [4]:
#Copy the dataset over to another variable so that we can begin our preprocessing
unprocessed_data = raw_data.copy()
unprocessed_data

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
0,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] GRACE 340 g",4447347,326.62
1,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] NUPAK 340 g",4449647,284.87
2,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] EVE 340 g",4446447,294.62
3,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] LASCO 340 g",4448147,310.04
4,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] MIRACLE 340 g",4449247,266.19
5,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] CARIBBEAN ...",4482547,0.00
6,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"CORNED BEEF (REGULAR, CANNED) [TX] OTHER 340 g",4449747,308.70
7,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] GRACE...,6947334,79.41
8,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] BRUNS...,6944434,73.71
9,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] KENDE...,6982734,71.72
10,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] LASCO...,6948134,67.68
11,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,MACKEREL (CANNED) (In Tomato Sauce) [NT] OTHER...,6949734,69.51
12,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (CANNED, In Soya Oil) [NT] BRUNSWICK ...",8744427,117.88
13,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (Canned, In Vegetable Oil) [NT] GRACE...",19147327,112.36
14,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"SARDINES (CANNED, In Soya Oil) [NT] OTHER 106 g",8749727,0.00
15,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,DRIED SALTED FISH [TX] BULK 1 kg,5344721,960.19
16,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHICKEN BACK [NT] LOCAL 1 kg,3948621,308.00
17,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHICKEN BACK [NT] IMPORTED 1 kg,3947521,187.00
18,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"WHOLE CHICKEN (Grade A, Frozen) [NT] BEST DRES...",10243821,477.20
19,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,"WHOLE CHICKEN (Grade A, Frozen) [NT] CB 1 kg",10245121,456.30
20,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SKIMMED MILK POWDER [TX] LASCO - READIMILK 80 g,9050065,109.58
21,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,POWDERED WHOLE MILK [NT] LASCO 80 g,8048165,118.95
22,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,POWDERED WHOLE MILK [NT] ANCHOR 80 g,8043565,119.05
23,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SWEETENED CONDENSED MILK [TX] SERGE 392 g,91868123,272.84
24,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SWEETENED CONDENSED MILK [TX] BETTY 395 g,9144052,231.73
25,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] SERGE ISLAND 1 L,5750722,291.18
26,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] NESTLE 1 L,5749422,0.00
27,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,FRESH MILK (In Tetrapack) [NT] MIRACLE 1 L,5749222,245.45
28,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CHEESE (Processed) [TX] TASTEE 1 kg,3851221,1735.12
29,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,INFANT FORMULA [NT] LASCO STEP 1 400 g,6348253,567.46
...,...,...,...,...,...,...,...,...
970,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,BLEACH [TX] CHLORITE 475 mL,3445557,0.00
971,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,BATH SOAP [TX] PALMOLIVE (Asssorted) 110 g,3149828,107.13
972,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.00
973,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SHAMPOO [TX] ALBERTO V05 370 g,89434442,0.00
974,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,LOTION [TX] JERGENS (Original Scent) 295 mL,6847744,413.53
975,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,LOTION [TX] VASELINE INTENSIVE CARE 295 mL,6851444,432.17
976,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,POWDER [TX] LANDER 113 g,7748029,202.66
977,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,POWDER [TX] JOHNSON'S BABY POWDER 113 g,7747929,313.34
978,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOILET TISSUE [TX] ANY 400 sheets,9581854,69.85
979,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHPASTE (Regular) [TX] COLGATE (Cavity Prot...,99458280,129.27
980,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHPASTE (Regular) [TX] LASCO (Advanced Cavi...,9969166,119.95
981,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,TOOTHBRUSH [TX] COLGATE CLASSIC Each,9883069,0.00
982,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SANITARY NAPKINS [NT] STAYFREE MAXI (Regular w...,8650924,229.96
983,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SANITARY NAPKINS [NT] LIBRESSE MAXI (Regular W...,8648324,158.96
984,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] GRACE 340 g",4447347,377.00
985,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] NUPAK 340 g",4449647,311.00
986,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] EVE 340 g",4446447,306.00
987,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] LASCO 340 g",4448147,313.00
988,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] MIRACLE 340 g",4449247,273.00
989,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] CARIBBEAN ...",4482547,325.00
990,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"CORNED BEEF (REGULAR, CANNED) [TX] OTHER 340 g",4449747,320.00
991,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] GRACE...,6947334,76.00
992,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] BRUNS...,6944434,76.00
993,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] KENDE...,6982734,72.00
994,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] LASCO...,6948134,69.00
995,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,MACKEREL (CANNED) (In Tomato Sauce) [NT] OTHER...,6949734,65.00
996,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (CANNED, In Soya Oil) [NT] BRUNSWICK ...",8744427,118.00
997,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (Canned, In Vegetable Oil) [NT] GRACE...",19147327,124.00
998,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,"SARDINES (CANNED, In Soya Oil) [NT] OTHER 106 g",8749727,92.00
999,95,2018-04-12,KAMLYN'S,PORT ANTONIO,Portland,DRIED SALTED FISH [TX] BULK 1 kg,5344721,897.60

In [5]:
#Let's see what quick, useful information is present on this dataset
unprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
OutletID       1000 non-null int64
SurveyDate     1000 non-null object
Outlet_Name    1000 non-null object
Town           1000 non-null object
Parish         1000 non-null object
Item           1000 non-null object
ItemID         1000 non-null int64
Price          1000 non-null object
dtypes: int64(2), object(6)
memory usage: 62.6+ KB

In [6]:
#optional
#This provides a more comprehensive report on the dataset. However, this requires a separate conda install to utilize this package
pp.ProfileReport(unprocessed_data)

# Initial Data Preprocessing

#### **<font color=blue>Notice that the SurveyDate and Price columns don't seem to be of the correct data types. Let's fix that in the next subsequent cell executions</font>**

In [7]:
#Let's check to see if we have any duplicates first
print("We have", unprocessed_data.duplicated(subset=None, keep='first').sum(),"duplicate record(s)")

We have 0 duplicate record(s)

### If we had duplicates, we could've used the below command to get rid of them

#### df = df.drop_duplicates(subset=[list_of_column_names], keep='first') <font color=blue>[generic command]</font>
#### <font color=green> df = unprocessed_data.drop_duplicates(keep='first') </font>

In [8]:
#What are the range of values for the SurveyDate column?
unprocessed_data.SurveyDate.unique()

array(['2018-04-12'], dtype=object)

In [9]:
#Change the SurveyDate column to a datetime object
unprocessed_data.SurveyDate = pd.to_datetime(unprocessed_data.SurveyDate, format='%Y-%m-%d')

In [10]:
#What are the range of values for the Price column?
unprocessed_data.Price.unique()
#This list is too long. We might potentially miss something by just glancing over the values

array(['326.62', '284.87', '294.62', '310.04', '266.19', '0.00', '308.70',
       '79.41', '73.71', '71.72', '67.68', '69.51', '117.88', '112.36',
       '960.19', '308.00', '187.00', '477.20', '456.30', '109.58',
       '118.95', '119.05', '272.84', '231.73', '291.18', '245.45',
       '1735.12', '567.46', '647.28', '1785.30', '135.65', '234.50',
       '186.49', '205.41', '201.29', '186.29', '178.23', '245.25',
       '135.33', '111.32', '106.47', '182.89', '169.98', '391.77',
       '85.61', '73.46', '\\N', '96.48', '122.36', '116.52', '152.39',
       '76.19', '148.87', '62.03', '52.64', '47.62', '31.45', '35.52',
       '56.70', '313.32', '306.00', '230.96', '289.05', '251.65',
       '148.93', '174.46', '148.05', '351.10', '146.30', '175.60',
       '131.70', '234.10', '292.60', '376.63', '254.20', '425.63',
       '63.89', '77.94', '33.79', '82.70', '214.91', '62.82', '56.47',
       '92.31', '81.82', '103.24', '437.53', '405.52', '60.31', '113.23',
       '233.83', '377.46', '331.33', '315.95', '308.96', '77.50', '68.15',
       '62.28', '130.80', '115.00', '974.91', '189.82', '438.90',
       '133.98', '132.89', '257.35', '241.16', '313.75', '1800.00',
       '585.60', '688.75', '145.57', '237.37', '208.80', '192.60',
       '275.00', '138.43', '186.82', '458.13', '115.90', '96.27',
       '110.55', '160.00', '82.50', '161.54', '65.99', '56.00', '50.00',
       '37.70', '427.58', '63.70', '319.36', '306.97', '232.07', '263.13',
       '183.75', '137.50', '215.60', '184.80', '331.25', '268.84',
       '489.33', '73.92', '86.50', '84.50', '110.00', '233.00', '68.44',
       '106.31', '99.03', '115.04', '253.15', '421.41', '64.08', '240.00',
       '175.00', '398.27', '329.00', '315.00', '333.00', '298.00',
       '330.00', '340.00', '89.00', '80.00', '76.00', '73.24', '74.00',
       '125.00', '126.00', '990.00', '220.00', '484.00', '128.35',
       '145.00', '265.00', '253.00', '323.00', '1518.00', '620.00',
       '665.00', '1895.00', '135.00', '246.00', '206.00', '219.00',
       '211.40', '225.00', '250.00', '146.00', '134.00', '185.00',
       '240.43', '500.00', '390.60', '94.93', '129.00', '127.00',
       '158.00', '81.00', '162.56', '76.11', '57.00', '51.00', '35.00',
       '342.00', '245.00', '278.00', '266.00', '155.00', '183.00',
       '352.00', '264.00', '550.00', '286.00', '381.00', '480.00',
       '68.00', '83.00', '139.00', '88.00', '67.00', '99.00', '109.00',
       '243.42', '420.00', '133.00', '238.00', '241.00', '342.93',
       '309.89', '81.90', '78.76', '76.56', '77.14', '149.46', '123.14',
       '98.00', '1149.51', '429.00', '242.00', '468.65', '455.60',
       '132.13', '133.95', '279.60', '250.17', '318.13', '296.96',
       '591.08', '687.71', '146.34', '269.36', '242.58', '237.57',
       '198.00', '151.24', '135.82', '574.11', '108.30', '95.00', '55.00',
       '47.60', '39.40', '67.27', '348.11', '346.93', '240.99', '243.66',
       '160.38', '189.78', '400.00', '441.00', '143.00', '423.00',
       '436.88', '433.41', '468.50', '64.91', '99.23', '58.25', '99.25',
       '299.28', '67.78', '97.03', '133.52', '508.56', '64.27', '145.26',
       '250.54', '345.26', '346.46', '72.32', '58.96', '133.19', '120.06',
       '98.55', '978.60', '127.57', '127.96', '266.51', '242.98',
       '343.92', '1757.99', '155.42', '225.93', '214.41', '151.61',
       '159.79', '108.73', '149.95', '138.88', '158.38', '59.72', '68.61',
       '262.30', '303.00', '204.55', '200.45', '443.47', '78.06', '69.43',
       '96.96', '370.68', '88.17', '186.01', '385.00', '345.00', '325.00',
       '85.00', '75.00', '70.00', '1012.00', '209.00', '440.00', '300.00',
       '600.00', '685.00', '140.00', '200.00', '270.00', '138.00',
       '165.00', '295.00', '120.00', '390.00', '310.00', '230.00',
       '260.00', '320.00', '450.00', '90.00', '100.00', '60.00', '350.00',
       '1254.00', '202.40', '290.00', '1580.00', '570.00', '640.00',
       '1760.00', '195.00', '180.00', '132.00', '148.00', '65.00',
       '40.00', '301.00', '190.00', '377.41', '330.81', '314.50',
       '283.05', '312.17', '83.96', '72.96', '71.96', '68.96', '69.96',
       '143.96', '117.96', '91.96', '961.08', '303.60', '178.20',
       '477.96', '451.96', '119.95', '125.96', '278.39', '216.64',
       '1647.26', '1790.96', '136.26', '239.94', '200.33', '207.96',
       '192.96', '147.91', '115.29', '186.96', '187.96', '99.96', '93.46',
       '107.76', '280.00', '122.28', '152.96', '75.96', '158.96', '65.96',
       '55.96', '46.96', '37.96', '59.96', '323.82', '297.03', '220.14',
       '224.80', '217.81', '174.70', '202.66', '177.03', '315.96',
       '286.96', '228.96', '115.96', '216.96', '231.96', '330.96',
       '215.96', '400.71', '249.96', '431.00', '62.86', '81.50', '53.54',
       '52.38', '266.74', '86.16', '257.42', '258.58', '50.05', '90.82',
       '74.51', '107.13', '413.53', '432.17', '313.34', '69.85', '129.27',
       '229.96', '377.00', '311.00', '313.00', '273.00', '72.00', '69.00',
       '118.00', '124.00', '92.00', '897.60'], dtype=object)

In [11]:
#Let's try to filter out non-numeric values in the Price column
unprocessed_data[pd.to_numeric(unprocessed_data.Price, errors='coerce').isnull()]

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
52,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
175,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
232,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,BLEACH [TX] CHLORITE 475 mL,3445557,\N
234,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,\N
241,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,TOOTHPASTE (Regular) [TX] COLGATE (Cavity Prot...,99458280,\N
298,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
349,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,POWDERED LAUNDRY DETERGENT [TX] BREEZE (Mul...,78442279,\N
350,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,POWDERED LAUNDRY DETERGENT [TX] ARIEL 400 g,7843653,\N
354,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,BLEACH [TX] CHLORO-DO 475 mL,3445657,\N
355,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,BLEACH [TX] CHLORITE 475 mL,3445557,\N
357,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,\N
364,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,TOOTHPASTE (Regular) [TX] COLGATE (Cavity Prot...,99458280,\N
421,173,2018-04-12,VALUE MASTER,NEGRIL,Westmoreland,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
544,76,2018-04-12,HI-LO SUPERMARKET,NEGRIL,Westmoreland,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
634,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,"WHOLE CHICKEN (Grade A, Frozen) [NT] CB 1 kg",10245121,\N
650,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,COOKING OIL [NT] CHEF 500 mL,4245359,\N
651,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,COOKING OIL [NT] LIDER 500 mL,4248459,\N
664,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,REFINED/GRANULATED SUGAR [TX] OTHER 1 kg,12549721,\N
667,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
707,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,EGGS [TX] IMPORTED 1 doz,3047520,\N
713,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,LIGHT BULB [TX] CARIB 100 watt,6744925,\N
724,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,BLEACH [TX] CHLORITE 475 mL,3445557,\N
726,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,\N
764,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,FRESH MILK (In Tetrapack) [NT] NESTLE 1 L,5749422,\N
777,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,COOKING OIL [NT] BULK 1 L,4244722,\N
790,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N
847,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,BLEACH [TX] CHLORITE 475 mL,3445557,\N
849,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,\N
858,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,TOOTHBRUSH [TX] COLGATE CLASSIC Each,9883069,\N
882,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,POWDERED WHOLE MILK [NT] LASCO 80 g,8048165,\N
886,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,FRESH MILK (In Tetrapack) [NT] SERGE ISLAND 1 L,5750722,\N
887,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,FRESH MILK (In Tetrapack) [NT] NESTLE 1 L,5749422,\N
888,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,FRESH MILK (In Tetrapack) [NT] MIRACLE 1 L,5749222,\N
890,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,INFANT FORMULA [NT] LASCO STEP 1 400 g,6348253,\N
891,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,INFANT FORMULA [NT] NESTLE LACTOGEN 1 400 g,6349553,\N
913,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,CORNMEAL (Refined) [NT] BULK 1 kg,19044721,\N

In [12]:
#Let's impute these values with NaN's for now
unprocessed_data.Price = unprocessed_data.Price.replace('\\N', np.NaN)

In [13]:
#Let's change the data type of the column now
unprocessed_data.Price = pd.to_numeric(unprocessed_data.Price)

In [14]:
#Let's see if all our data types are now in order
unprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
OutletID       1000 non-null int64
SurveyDate     1000 non-null datetime64[ns]
Outlet_Name    1000 non-null object
Town           1000 non-null object
Parish         1000 non-null object
Item           1000 non-null object
ItemID         1000 non-null int64
Price          964 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 62.6+ KB

# Data Preprocessing Cont'd

In [15]:
#This is one such item that had "\N" as a price value. Let's see what other prices it was being sold for
unprocessed_data[unprocessed_data.Item == 'SHAMPOO [TX] WHITE RAIN 443 mL']

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
111,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.0
234,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,NaN
357,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,NaN
480,173,2018-04-12,VALUE MASTER,NEGRIL,Westmoreland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.0
603,76,2018-04-12,HI-LO SUPERMARKET,NEGRIL,Westmoreland,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.0
726,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,NaN
849,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,NaN
972,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,SHAMPOO [TX] WHITE RAIN 443 mL,8951655,0.0

### <font color=green>Since we've realized that they all contain 0, we can drop these rows since they will be of no use to us in further analyses</font>

In [16]:
# Get names of indexes for which column Item has value of 'SHAMPOO [TX] WHITE RAIN 443 mL'
indexNames = unprocessed_data[unprocessed_data.Item == 'SHAMPOO [TX] WHITE RAIN 443 mL'].index

# Delete these row indexes from the dataFrame
unprocessed_data.drop(indexNames, inplace=True)

In [17]:
#Let's check to see if they're still there
unprocessed_data[unprocessed_data.Item == 'SHAMPOO [TX] WHITE RAIN 443 mL']
#No longer there

Empty DataFrame
Columns: [OutletID, SurveyDate, Outlet_Name, Town, Parish, Item, ItemID, Price]
Index: []

In [18]:
#Here's another item that had "\N" as a price value. Let's see what other prices it was being sold for
unprocessed_data[unprocessed_data.Item == 'COOKING OIL [NT] CHEF 500 mL']

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
35,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,205.41
158,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,0.00
281,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,COOKING OIL [NT] CHEF 500 mL,4245359,0.00
404,173,2018-04-12,VALUE MASTER,NEGRIL,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,242.58
527,76,2018-04-12,HI-LO SUPERMARKET,NEGRIL,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,242.58
650,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,COOKING OIL [NT] CHEF 500 mL,4245359,NaN
773,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,COOKING OIL [NT] CHEF 500 mL,4245359,0.00
896,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,COOKING OIL [NT] CHEF 500 mL,4245359,0.00

In [19]:
#Let's impute the 0 values with NaN's, then find the mean
unprocessed_data.Price = unprocessed_data.Price.replace(0, np.NaN)
cooking_oil_chef_500ml_mean = unprocessed_data.groupby('Item').get_group('COOKING OIL [NT] CHEF 500 mL')['Price'].mean()
cooking_oil_chef_500ml_mean

230.19000000000003

In [20]:
#Now let's impute the NaN's with the mean for each
unprocessed_data.loc[(unprocessed_data.Item == 'COOKING OIL [NT] CHEF 500 mL') & (unprocessed_data.Price.isnull()), 'Price']  = cooking_oil_chef_500ml_mean

In [21]:
#HLet's see if it worked
unprocessed_data[unprocessed_data.Item == 'COOKING OIL [NT] CHEF 500 mL']

,OutletID,SurveyDate,Outlet_Name,Town,Parish,Item,ItemID,Price
35,47,2018-04-12,D & Y SUPERMARKET,SAVANNA-LA-MAR,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,205.41
158,114,2018-04-12,MEAT PLUS,SAVANNA-LA-MAR,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,230.19
281,243,2018-04-12,SHOPPER'S PRIDE,BUFF BAY,Portland,COOKING OIL [NT] CHEF 500 mL,4245359,230.19
404,173,2018-04-12,VALUE MASTER,NEGRIL,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,242.58
527,76,2018-04-12,HI-LO SUPERMARKET,NEGRIL,Westmoreland,COOKING OIL [NT] CHEF 500 mL,4245359,242.58
650,192,2018-04-12,ZHEN'S WHOLESALE,CAMBRIDGE,St. James,COOKING OIL [NT] CHEF 500 mL,4245359,230.19
773,101,2018-04-12,LEE'S VALUE PLUS,HOPEWELL,Hanover,COOKING OIL [NT] CHEF 500 mL,4245359,230.19
896,223,2018-04-12,SUPER PLUS (MID WAY MALL),MANDEVILLE,Manchester,COOKING OIL [NT] CHEF 500 mL,4245359,230.19

In [22]:
#Remember those 8 rows we dropped earlier on that contained SHAMPOO [TX] WHITE RAIN 443 mL as the item? They're no longer 
#in the dataset, hence, we have fewer rows. Let's reset our indices accordingly
unprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 992 entries, 0 to 999
Data columns (total 8 columns):
OutletID       992 non-null int64
SurveyDate     992 non-null datetime64[ns]
Outlet_Name    992 non-null object
Town           992 non-null object
Parish         992 non-null object
Item           992 non-null object
ItemID         992 non-null int64
Price          640 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 69.8+ KB

In [23]:
#Our indices have been reset. Let's do a quick check to confirm
unprocessed_data.reset_index(drop=False, inplace=True)
unprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 9 columns):
index          992 non-null int64
OutletID       992 non-null int64
SurveyDate     992 non-null datetime64[ns]
Outlet_Name    992 non-null object
Town           992 non-null object
Parish         992 non-null object
Item           992 non-null object
ItemID         992 non-null int64
Price          640 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 69.8+ KB

 #  <font color=blue>From here, we can impute more variables and do further cleaning before we are able to perform any analyses of the sort. However, try to complete the task of preprocessing by yourself based on what you've learnt thus far</font>

## <font color=green>Happy coding!</font>